version: "3.8"

services:
  neo4j:
    image: neo4j:5.13
    container_name: builder-ki-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/builderki123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: builder-ki-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL= https://unquarrelling-chemosynthetically-kelsi.ngrok-free.dev
      # Add these for connecting to Supabase/Neo4j
      - GENERIC_TIMEZONE=America/New_York
      - NODE_FUNCTION_ALLOW_EXTERNAL=neo4j-driver
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:
  n8n_data:
